name: flutter

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter format .
      - name: "Check that there are no changes after formatting"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo Working directory not clean after formatting. Please apply the
            echo following changes:
            git diff
            false
          fi
      - run: flutter analyze
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1

  build:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        flutter_channel: [beta, stable]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_channel }}
      - working-directory: example
        # Testing on one platform (Android) is sufficient, since our plugin is
        # platform agnostic.
        run: flutter build apk --debug
